import streamlit as st
from PIL import Image
import numpy as np
from collections import Counter
import io

# Set page config
st.set_page_config(
    page_title="Barcode Encoder/Decoder",
    page_icon="📊",
    layout="wide"
)

def encode_barcode(text):
    """Encode text into a barcode image"""
    width, height = 800, 400
    step = 9
    img = np.ones((height, width), dtype=np.uint8) * 255  # white canvas

    x = 0
    for ch in text:
        if ch == ' ':
            bar_width = 1
            top, bottom = 150, 250
        else:
            pos = ord(ch.lower()) - ord('a')
            bar_width = pos + 1
            top, bottom = 10, 350

        img[top:bottom, x:x+bar_width] = 0
        x += bar_width + step

    return Image.fromarray(img)

def decode_barcode(img):
    """Decode a barcode image to text"""
    img = img.convert("L")
    arr = np.array(img)
    height, width = arr.shape
    mid = height // 2
    row = arr[mid] < 128

    # First pass: collect all white run lengths
    white_runs = []
    i = 0
    while i < width:
        if not row[i]:
            white_run = 0
            while i < width and not row[i]:
                white_run += 1
                i += 1
            white_runs.append(white_run)
        else:
            i += 1

    # Find the most common white run (between letters) and the next largest (between words)
    if white_runs:
        run_counts = Counter(white_runs)
        most_common = run_counts.most_common()
        letter_gap = most_common[0][0]
        # Find a gap at least twice as big as letter_gap (likely a space)
        space_gap = max([run for run in white_runs if run > letter_gap * 1.5], default=letter_gap * 2)
        threshold = (letter_gap + space_gap) // 2
    else:
        threshold = 3  # fallback

    # Second pass: decode
    result = ""
    i = 0
    while i < width:
        if row[i]:
            w = 0
            while i < width and row[i]:
                w += 1
                i += 1
            if 1 <= w <= 26:
                result += chr(ord("a") + (w - 1))
            else:
                result += "?"
        else:
            white_run = 0
            while i < width and not row[i]:
                white_run += 1
                i += 1
            if white_run >= threshold:
                result += " "

    return result

# App title and description
st.title("📊 Barcode Encoder & Decoder")
st.markdown("Convert text to custom barcodes and decode them back!")

# Create tabs
tab1, tab2 = st.tabs(["🔤 Encode Text", "🔍 Decode Barcode"])

# Encode Tab
with tab1:
    st.header("Encode Text to Barcode")
    
    # Input text
    input_text = st.text_input(
        "Enter text to encode:",
        value="Syeda Sara Afzaal",
        help="Enter any text with letters and spaces"
    )
    
    col1, col2 = st.columns([1, 3])
    
    with col1:
        if st.button("🎨 Generate Barcode", type="primary", use_container_width=True):
            if input_text:
                with st.spinner("Generating barcode..."):
                    barcode_img = encode_barcode(input_text)
                    st.session_state.barcode_img = barcode_img
                    st.success("✅ Barcode generated successfully!")
            else:
                st.warning("⚠️ Please enter some text to encode")
    
    # Display barcode if generated
    if 'barcode_img' in st.session_state:
        st.image(st.session_state.barcode_img, caption="Generated Barcode", use_container_width=True)
        
        # Download button
        buf = io.BytesIO()
        st.session_state.barcode_img.save(buf, format="PNG")
        byte_im = buf.getvalue()
        
        st.download_button(
            label="⬇️ Download Barcode",
            data=byte_im,
            file_name="barcode.png",
            mime="image/png",
            use_container_width=True
        )
    
    # Explanation
    with st.expander("ℹ️ How does encoding work?"):
        st.markdown("""
        **Encoding Algorithm:**
        - Each letter (a-z) is represented by a black bar of width 1-26 pixels
        - 'a' = 1 pixel wide, 'b' = 2 pixels, ..., 'z' = 26 pixels
        - Spaces are represented by shorter bars (150-250 height vs 10-350)
        - Bars are separated by 9 pixels of white space
        """)

# Decode Tab
with tab2:
    st.header("Decode Barcode to Text")
    
    # File uploader
    uploaded_file = st.file_uploader(
        "Upload a barcode image:",
        type=['png', 'jpg', 'jpeg'],
        help="Upload a barcode image generated by this app"
    )
    
    if uploaded_file is not None:
        # Display uploaded image
        col1, col2 = st.columns(2)
        
        with col1:
            st.subheader("Uploaded Barcode")
            uploaded_img = Image.open(uploaded_file)
            st.image(uploaded_img, use_container_width=True)
        
        with col2:
            st.subheader("Decoded Text")
            if st.button("🔍 Decode Barcode", type="primary", use_container_width=True):
                with st.spinner("Decoding barcode..."):
                    decoded_text = decode_barcode(uploaded_img)
                    st.session_state.decoded_text = decoded_text
            
            if 'decoded_text' in st.session_state:
                st.success("✅ Decoding complete!")
                st.code(st.session_state.decoded_text, language=None)
    
    # Explanation
    with st.expander("ℹ️ How does decoding work?"):
        st.markdown("""
        **Decoding Algorithm:**
        1. Convert image to grayscale and read the middle row
        2. Identify black bars (bars represent letters)
        3. Measure bar widths to determine letters
        4. Analyze white space gaps to identify word boundaries
        5. Reconstruct the original text
        """)

# Footer
st.markdown("---")
st.markdown(
    """
    <div style='text-align: center'>
        <p>Made with ❤️ using Streamlit | 
        <a href='https://github.com/sawraw404/Barcode-Reader' target='_blank'>GitHub Repository</a></p>
    </div>
    """,
    unsafe_allow_html=True
)